### ISSUE TITLE
Deprecation warning about using test as filters

### ISSUE THREAD

**Issue by CumpsD** [Oefenweb/ansible-pip#9]
On ansible 2.6, I am getting the following with this role:

> [DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|changed` instead use `result is changed`. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Related to:
https://github.com/Oefenweb/ansible-pip/blob/8f82b1bf23beb5c9af4316ccfd77639bc2bc2fc6/tasks/main.yml#L43

**Comment by tersmitten** [comment]
Already fixed
